[environments.development]
store = "hormone-concept.myshopify.com"
theme = "181851619595"

[environments.copy]
store = "hormone-concept.myshopify.com"
theme = "181622014219"

[environments.sandbox]
store = "hormone-concept.myshopify.com"
theme = "181831205131"
